# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20161110_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='./static/images'),
        ),
    ]
