# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20161111_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
